# custom flags for a more clean instruction set

SOURCE=18_math_functions.c 18_main.c
TARGET=app.run
FLAGS=-g3 -Wall
COMPILER=gcc

all:
	@$(COMPILER) $(FLAGS) $(SOURCE) -o $(TARGET)

clean:
	@rm -f $(TARGET)