# custom flags for a more clean instruction set

SOURCE=math_functions.c main.c
TARGET=app.run
FLAGS=-g3 -Wall
COMPILER=gcc

all:
	@$(COMPILER) $(FLAGS) $(SOURCE) -o $(TARGET)

clean:
	@rm -f $(TARGET)